export const en = {
  “/”: {
title_privacy: "Komexxe Privacy Policy"
title_update: "Last updated: January 1, 2021."
text_title_update_1: "We know that you care how information about you is used and shared, and we appreciate your trust that we will do so carefully and sensibly. This Privacy Notice describes how Komexxe.com collect and process your personal information through Komexxe websites, devices, products, services, online and physical stores, and applications that reference this Privacy Notice (together \"Komexxe Services\"). By using Komexxe Services, you are consenting to the practices described in this Privacy Notice."
text_title_update_2: "This Privacy Policy applies only to our online activities and is valid for visitors to our website with regard to the information that they shared and/or collect in Komexxe. This policy is not applicable to any information collected offline or via channels other than this website."
title_consentement: "Consent"
text_consentement: "By using our website, you hereby consent to our Privacy Policy and agree to its terms."
title_information: "Information we collect"
text_title_info_1: "The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information."
text_title_info_2: "If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide."
text_title_info_3: "When you register for an Account, we may ask for your contact information, including items such as name, address, email address, and telephone number."
title_use_info: "How we use your information"
after_title_use_infos: "We use the information we collect in various ways, including to:"
text_after_use_infos_1: "- Purchase and delivery of products and services. We use your personal information to take and handle orders, deliver products and services, process payments, and communicate with you about orders, products and services, and promotional offers."
text_after_use_infos_2: "- Provide, troubleshoot, and improve Komexxe Services. We use your personal information to provide functionality, analyze performance, fix errors, and improve the usability and effectiveness of the Komexxe Services."
text_after_use_infos_3: "- Recommendations and personalization. We use your personal information to recommend features, products, and services that might be of interest to you, identify your preferences, and personalize your experience with Komexxe Services."
text_after_use_infos_4: "- Provide voice, image and camera services. When you use our voice, image and camera services, we use your voice input, images, videos, and other personal information to respond to your requests, provide the requested service to you, and improve our services. For more information about Alexa voice services."
text_after_use_infos_5: "- Comply with legal obligations. In certain cases, we collect and use your personal information to comply with laws. For instance, we collect from sellers information regarding place of establishment and bank account information for identity verification and other purposes."
text_after_use_infos_6: "- Communicate with you. We use your personal information to communicate with you in relation to Komexxe Services via different channels (e.g., by phone, email, chat)."
text_after_use_infos_7: "- Advertising. We use your personal information to display interest-based ads for features, products, and services that might be of interest to you. We do not use information that personally identifies you to display interest-based ads."
text_after_use_infos_8: "- Fraud Prevention and Credit Risks. We use personal information to prevent and detect fraud and abuse in order to protect the security of our customers, Komexxe, and others. We may also use scoring methods to assess and manage credit risks."
title_protection: "Third Party Privacy Policies"
text_title_protection: "Komexxe's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options."
title_privacy_rights: "Privacy Rights (Do Not Sell My Personal Information)"
after_title_privacy_rights: "Under the CCPA, among other rights, Cameroon consumers have the right to:"
text_after_title_privacy_1: "- Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers."
text_after_title_privacy_2: "- Request that a business delete any personal data about the consumer that a business has collected."
text_after_title_privacy_3: "- Request that a business that sells a consumer's personal data, not sell the consumer's personal data."
text_after_title_privacy_4: "If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us."
title_data_protection: "Data Protection Rights"
after_title_data_protection: "We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:"
text_title_data_protection_1: "- The right to access – You have the right to request copies of your personal data. We may charge you a small fee for this service."
text_title_data_protection_2: "- The right to rectification – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete."
text_title_data_protection_3: "- The right to erasure – You have the right to request that we erase your personal data, under certain conditions."
text_title_data_protection_4: "- The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions."
text_title_data_protection_5: "- The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions."
text_title_data_protection_6: "- The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions."
text_title_data_protection_7: "If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us."
title_children_protection: "Children Protection Right"
text_children_protection_1: "Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity."
text_children_protection_2: "Komexxe does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately, and we will do our best efforts to promptly remove such information from our records."
title_cookies: "Cookies"
text_title_cookies_1: "When you use our Services, we and selected third parties may use cookies and similar technologies to provide you with a better, faster and safer user experience or to show you personalized advertising. Cookies are small text files that are automatically created by your browser and stored on your device when you use the Services."
text_title_cookies_2: "Note that Komexxe has no access to or control over these cookies that are used by third-party advertisers."
},
};